version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
  commands:
    - pwd
    - ls -la
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - asdf plugin add dotnet
    - asdf install dotnet latest
    - asdf global dotnet latest
    - dotnet tool install -g docfx
    - ~/.dotnet/tools/docfx docs/docfx.json
    - cp docs/_site/* $READTHEDOCS_OUTPUT/html
