version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - echo $PATH
    - asdf plugin add dotnet
    - asdf install dotnet latest
    - asdf global dotnet latest
    - dotnet tool install docfx --global
    - ~/.dotnet/tools/docfx docs/docfx.json
    - cp docs/_site/* $READTHEDOCS_OUTPUT/html
