version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
  commands:
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - mkdir -p .dotnet-installation
    - cd .dotnet-installation
    - wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
    - chmod +x ./dotnet-install.sh
    - ./dotnet-install.sh --vesion 8.0.*
    - cd ..
    - dotnet tool update -g docfx
    - cd docs
    - docfx docfx.json
    - cd ..
    - cp docs/_site/* $READTHEDOCS_OUTPUT/html
