version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - wget https://dot.net/v1/dotnet-install.sh -O ~/dotnet-install.sh
    - chmod +x ~/dotnet-install.sh
    - ~/dotnet-install.sh --channel 8.0
    - ~/.dotnet/dotnet install docfx --global
    - ~/.dotnet/tools/docfx docs/docfx.json
    - cp docs/_site/* $READTHEDOCS_OUTPUT/html
