version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  commands:
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - echo $PATH
    - asdf plugin add dotnet
    - asdf install dotnet latest
    - asdf global dotnet latest
    - echo $PATH
    - dotnet --info
    - dotnet tool install docfx --tool-path ~/.asdf/shims
    - ls -la ~/.asdf/shims
    - docfx docs/docfx.json
    - cp docs/_site/* $READTHEDOCS_OUTPUT/html
